import type { MetadataRoute } from "next";

/**
 * Web App Manifest (served at /manifest.webmanifest) — makes the site
 * installable as "MockTestSeries". start_url is the Student Dashboard: a
 * signed-in student lands there, anyone else goes through the normal
 * proxy.ts → /login?callbackUrl=/student/dashboard flow. Colors are the
 * default dark theme's background (app/globals.css) so the splash screen
 * matches the first paint; icons are generated by
 * scripts/generate-pwa-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "MockTestSeries",
    short_name: "MockTestSeries",
    description: "Online mock tests, previous year papers and AI-powered explanations for medical officer exams.",
    start_url: "/student/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "any",
    background_color: "#000000",
    theme_color: "#000000",
    lang: "en",
    dir: "ltr",
    categories: ["education"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
