import type { Metadata } from "next";

import { Container } from "@/components/common/Container";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How MockTestSeries.in collects, uses and protects your data.",
};

export default function PrivacyPage() {
  return (
    <Container className="max-w-[760px] py-[clamp(28px,4vw,48px)]">
      <h1 className="font-display text-[clamp(28px,3.4vw,36px)] font-bold tracking-[-.02em] text-text-heading">
        Privacy Policy
      </h1>
      <p className="mt-3 rounded-[10px] border border-brand-accent-border bg-brand-accent-tint px-4 py-3 text-sm text-brand-accent-text">
        Draft starting policy — replace with a version reviewed by qualified counsel before
        relying on it as your binding privacy policy.
      </p>

      <div className="mt-6 flex flex-col gap-6 text-[15px] leading-relaxed text-text-muted">
        <section>
          <h2 className="text-base font-extrabold text-text-heading">What we collect</h2>
          <p className="mt-1.5">
            Account details you provide at registration (name, email, optionally phone), and
            data generated by using the platform — test attempts, answers, scores and analytics
            derived from them.
          </p>
        </section>
        <section>
          <h2 className="text-base font-extrabold text-text-heading">How we use it</h2>
          <p className="mt-1.5">
            To run your account, show your test history and analysis, generate AI explanations
            for questions you attempt, and improve the platform. We don&apos;t sell your personal
            data.
          </p>
        </section>
        <section>
          <h2 className="text-base font-extrabold text-text-heading">Data retention</h2>
          <p className="mt-1.5">
            We keep account and attempt data for as long as your account is active. You can
            request deletion of your account and associated data at any time.
          </p>
        </section>
        <section>
          <h2 className="text-base font-extrabold text-text-heading">Your rights</h2>
          <p className="mt-1.5">
            You can request a copy of your data or ask us to delete it by emailing{" "}
            <a href="mailto:support@mocktestseries.in" className="font-bold text-primary">
              support@mocktestseries.in
            </a>
            .
          </p>
        </section>
      </div>
    </Container>
  );
}
