import type { BulkImportRow, ImportParseMode } from "@/lib/bulk-import";

/**
 * JSON question files for the ONE Bulk Import pipeline (docs/JSON-IMPORT.md).
 *
 * JSON is only another way to write the rows a CSV/XLSX already carries:
 * this module turns the canonical `mocktestseries.questions/v1` document into
 * exactly the `BulkImportRow` strings the spreadsheet parsers produce (the
 * Rich-mode image / list cell grammar included), so staging, validation,
 * duplicate detection, preview, import, history and rollback are unchanged.
 *
 * Pure (no DB, no filesystem). Structural problems are reported per question
 * as `Question <n> › <field>: …` and refuse the whole file — a JSON file is
 * generated by a tool, so a broken one is fixed at the source, not row by row.
 * Content rules (taxonomy, answers, images, duplicates…) stay with the
 * existing validators, so their messages and severities are the same for
 * every format.
 */

export const JSON_IMPORT_SCHEMA = "mocktestseries.questions/v1";

export const JSON_IMPORT_LIMITS = {
  /** Same as the upload route's file limit. */
  maxBytes: 10 * 1024 * 1024,
  maxQuestions: 2000,
  maxDepth: 12,
} as const;

/** Name of the manifest inside a ZIP package (any folder depth; exactly one). */
export const JSON_PACKAGE_MANIFEST = "questions.json";

export class JsonImportError extends Error {
  constructor(public readonly problems: string[]) {
    super(problems.length === 1 ? problems[0] : `${problems.length} problems in the JSON file: ${problems.slice(0, 5).join(" · ")}${problems.length > 5 ? " · …" : ""}`);
    this.name = "JsonImportError";
  }
}

type Json = null | boolean | number | string | Json[] | { [k: string]: Json };
type Obj = { [k: string]: Json };

const LABELS = ["A", "B", "C", "D"] as const;

const QUESTION_KEYS = new Set([
  "code", "questionNumber", "exam", "year", "paperCode", "subject", "topic", "subtopic",
  "type", "contentFormat", "question", "options", "correct", "explanation", "difficulty",
  "source", "status", "review", "matchLists",
]);
/** Fields a document may set once for every question. */
const DEFAULT_KEYS = new Set(["exam", "year", "paperCode", "subject", "topic", "subtopic", "type", "contentFormat", "difficulty", "source"]);

const isObj = (v: unknown): v is Obj => typeof v === "object" && v !== null && !Array.isArray(v);

function depthOf(v: unknown, d = 0): number {
  if (d > JSON_IMPORT_LIMITS.maxDepth) return d;
  if (Array.isArray(v)) return v.reduce<number>((m, x) => Math.max(m, depthOf(x, d + 1)), d + 1);
  if (isObj(v)) return Object.values(v).reduce<number>((m, x) => Math.max(m, depthOf(x, d + 1)), d + 1);
  return d;
}

/** Content that needs Rich mode (formulas, images, MSQ/MTF, explanation images). */
function richFeatures(q: Obj, d: Obj): string[] {
  const out: string[] = [];
  const type = String(q.type ?? d.type ?? "").toUpperCase().replace(/[^A-Z]/g, "");
  if (type && !["SINGLECORRECT", "MCQ", "SINGLE"].includes(type)) out.push(`type ${String(q.type ?? d.type)}`);
  const fmt = String(q.contentFormat ?? d.contentFormat ?? "").toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (fmt && fmt !== "PLAIN" && fmt !== "TEXT") out.push(`contentFormat ${String(q.contentFormat ?? d.contentFormat)}`);
  if (q.matchLists !== undefined) out.push("matchLists");
  const hasImages = (v: Json | undefined) => isObj(v) && Array.isArray(v.images) && v.images.length > 0;
  if (hasImages(q.question)) out.push("question images");
  if (hasImages(q.explanation)) out.push("explanation images");
  if (Array.isArray(q.options) && q.options.some(hasImages)) out.push("option images");
  if (isObj(q.options) && Object.values(q.options).some(hasImages)) out.push("option images");
  if (q.review !== undefined) out.push("review");
  return out;
}

interface Ctx {
  n: number;
  problems: string[];
}
const fail = (c: Ctx, field: string, message: string) => c.problems.push(`Question ${c.n} › ${field}: ${message}`);

/** A scalar field: string, or a number / boolean written as JSON (year 2025, questionNumber 7). */
function scalar(c: Ctx, field: string, v: Json | undefined): string {
  if (v === undefined || v === null) return "";
  if (typeof v === "string") return v.trim();
  if (typeof v === "number" && Number.isFinite(v)) return String(v);
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  fail(c, field, "must be a string or a number.");
  return "";
}

/** Text that keeps its line breaks (question / option / explanation). */
function text(c: Ctx, field: string, v: Json | undefined): string {
  if (v === undefined || v === null) return "";
  if (typeof v === "string") return v.trim();
  if (typeof v === "number" && Number.isFinite(v)) return String(v);
  fail(c, field, "must be a string.");
  return "";
}

/** `{file, alt?, decorative?}` (or a bare "file.png") → the cell grammar `file :: alt`. */
function imageRefs(c: Ctx, field: string, v: Json | undefined): string {
  if (v === undefined || v === null) return "";
  if (!Array.isArray(v)) {
    fail(c, field, "must be an array of images.");
    return "";
  }
  const parts: string[] = [];
  v.forEach((img, i) => {
    const f = `${field}[${i}]`;
    const ref = typeof img === "string" ? { file: img } : isObj(img) ? img : null;
    if (!ref || typeof ref.file !== "string" || !ref.file.trim()) {
      fail(c, f, 'needs a "file" (the image file name inside the ZIP).');
      return;
    }
    const file = ref.file.trim();
    // The cell grammar reserves these; the file-name rules themselves stay with the existing validator.
    if (/[|\r\n]|::|@@/.test(file)) {
      fail(c, `${f}.file`, `"${file.slice(0, 60)}" contains a reserved character (|, ::, @@ or a line break).`);
      return;
    }
    if (ref.decorative === true) {
      parts.push(`${file} :: decorative`);
      return;
    }
    if (ref.alt !== undefined && ref.alt !== null && typeof ref.alt !== "string") {
      fail(c, `${f}.alt`, "must be a string.");
      return;
    }
    const alt = typeof ref.alt === "string" ? ref.alt.trim() : "";
    if (/[|\r\n]|::|@@/.test(alt)) {
      fail(c, `${f}.alt`, "must be one line without |, :: or @@.");
      return;
    }
    if (/^decorative$/i.test(alt)) {
      fail(c, `${f}.alt`, 'use "decorative": true instead of the alt text "decorative".');
      return;
    }
    parts.push(alt ? `${file} :: ${alt}` : file);
  });
  return parts.join(" | ");
}

/** `"text"` or `{text, images}`. */
function content(c: Ctx, field: string, v: Json | undefined): { text: string; images: string } {
  if (isObj(v)) {
    for (const k of Object.keys(v)) if (k !== "text" && k !== "images") fail(c, `${field}.${k}`, "unknown field.");
    return { text: text(c, `${field}.text`, v.text), images: imageRefs(c, `${field}.images`, v.images) };
  }
  return { text: text(c, field, v), images: "" };
}

/**
 * options: `["…", "…", "…", "…"]`, `{"A": …, "B": …}` or
 * `[{"label": "A", "text": "…", "images": […], "correct": true}, …]`.
 * Exactly the four labels A–D (the platform's option model).
 */
function options(c: Ctx, v: Json | undefined): { byLabel: Record<string, { text: string; images: string }>; flagged: string[] } {
  const byLabel: Record<string, { text: string; images: string }> = {};
  const flagged: string[] = [];
  if (v === undefined || v === null) {
    fail(c, "options", "is required (four options A–D).");
    return { byLabel, flagged };
  }
  const put = (label: string, raw: Json, field: string) => {
    const L = label.trim().toUpperCase();
    if (!(LABELS as readonly string[]).includes(L)) {
      fail(c, field, `option label "${label}" is not one of A, B, C, D.`);
      return;
    }
    if (byLabel[L]) {
      fail(c, field, `option ${L} is given twice.`);
      return;
    }
    if (isObj(raw)) {
      for (const k of Object.keys(raw)) if (!["label", "text", "images", "correct"].includes(k)) fail(c, `${field}.${k}`, "unknown field.");
      if (raw.correct !== undefined && typeof raw.correct !== "boolean") fail(c, `${field}.correct`, "must be true or false.");
      if (raw.correct === true) flagged.push(L);
      byLabel[L] = { text: text(c, `${field}.text`, raw.text), images: imageRefs(c, `${field}.images`, raw.images) };
    } else byLabel[L] = { text: text(c, field, raw), images: "" };
  };
  if (Array.isArray(v)) {
    if (v.length !== 4) fail(c, "options", `has ${v.length} options; exactly 4 (A–D) are supported.`);
    v.slice(0, 4).forEach((o, i) => {
      const label = isObj(o) && o.label !== undefined ? String(o.label) : LABELS[i];
      put(label, o, `options[${i}]`);
    });
  } else if (isObj(v)) {
    const keys = Object.keys(v);
    if (keys.length !== 4) fail(c, "options", `has ${keys.length} options; exactly 4 (A–D) are supported.`);
    for (const k of keys) put(k, v[k], `options.${k}`);
  } else fail(c, "options", "must be an array or an object keyed A–D.");
  return { byLabel, flagged };
}

/** `"B"`, `"A,C"` or `["A","C"]` → the existing Correct cell; label checks stay with the validators. */
function correct(c: Ctx, v: Json | undefined, flagged: string[]): string {
  if (v === undefined || v === null) {
    if (flagged.length) return flagged.join(",");
    fail(c, "correct", 'is required (e.g. "B", or ["A","C"] for multiple correct).');
    return "";
  }
  let labels: string[];
  if (Array.isArray(v)) {
    if (v.some((x) => typeof x !== "string")) {
      fail(c, "correct", "must list option labels as strings.");
      return "";
    }
    labels = (v as string[]).map((x) => x.trim().toUpperCase());
  } else if (typeof v === "string") labels = v.split(/\s*,\s*/).map((x) => x.trim().toUpperCase()).filter(Boolean);
  else {
    fail(c, "correct", 'must be a label ("B") or a list of labels (["A","C"]).');
    return "";
  }
  if (flagged.length && [...labels].sort().join(",") !== [...flagged].sort().join(",")) {
    fail(c, "correct", `(${labels.join(",")}) disagrees with the options marked "correct": true (${flagged.join(",")}).`);
  }
  return labels.join(",");
}

/** `{listI: [{key, text, images}], listII: […]}` → the List I / List II cells. */
function matchList(c: Ctx, field: string, v: Json | undefined): string {
  if (!Array.isArray(v)) {
    fail(c, field, "must be an array of {key, text, images}.");
    return "";
  }
  return v
    .map((e, i) => {
      const f = `${field}[${i}]`;
      if (!isObj(e) || typeof e.key !== "string" || !/^([A-Za-z]{1,4}|\d{1,2})$/.test(e.key.trim())) {
        fail(c, f, 'needs a "key" such as "A", "I" or "1".');
        return "";
      }
      for (const k of Object.keys(e)) if (!["key", "text", "images"].includes(k)) fail(c, `${f}.${k}`, "unknown field.");
      const t = text(c, `${f}.text`, e.text);
      if (/[|\r\n]|@@/.test(t)) fail(c, `${f}.text`, "must be one line without | or @@ (write |x| as \\lvert x\\rvert).");
      const imgs = imageRefs(c, `${f}.images`, e.images);
      return `${e.key.trim()}. ${t}${imgs ? ` @@ ${imgs}` : ""}`;
    })
    .join("\n");
}

function toRow(q: Json, index: number, d: Obj, mode: ImportParseMode, problems: string[]): BulkImportRow | null {
  const c: Ctx = { n: index + 1, problems };
  if (!isObj(q)) {
    fail(c, "(question)", "must be an object.");
    return null;
  }
  for (const k of Object.keys(q)) if (!QUESTION_KEYS.has(k)) fail(c, k, "unknown field (see docs/JSON-IMPORT.md).");
  if (mode === "LEGACY") {
    const rich = richFeatures(q, d);
    if (rich.length) fail(c, rich[0], "needs Rich content mode — choose “Rich content” and upload again.");
  }
  const pick = (k: string) => (q[k] !== undefined ? q[k] : d[k]);
  const question = content(c, "question", q.question);
  const explanation = content(c, "explanation", q.explanation);
  const { byLabel, flagged } = options(c, q.options);
  const status = scalar(c, "status", q.status).toUpperCase();
  // JSON imports never publish: the question stays DRAFT until an admin publishes it after review.
  if (status && status !== "DRAFT") fail(c, "status", `"${status}" is not accepted — JSON imports are always saved as DRAFT.`);

  const row: BulkImportRow = {
    rowNumber: index + 1,
    exam: scalar(c, "exam", pick("exam")),
    examYear: scalar(c, "year", pick("year")),
    questionCode: scalar(c, "code", q.code) || undefined,
    questionNumber: scalar(c, "questionNumber", q.questionNumber) || undefined,
    subject: scalar(c, "subject", pick("subject")),
    topic: scalar(c, "topic", pick("topic")),
    subTopic: scalar(c, "subtopic", pick("subtopic")),
    source: scalar(c, "source", pick("source")),
    questionText: question.text,
    optionA: byLabel.A?.text ?? "",
    optionB: byLabel.B?.text ?? "",
    optionC: byLabel.C?.text ?? "",
    optionD: byLabel.D?.text ?? "",
    correctAnswer: correct(c, q.correct, flagged),
    explanation: explanation.text || undefined,
    difficulty: scalar(c, "difficulty", pick("difficulty")).toUpperCase(),
    image: undefined,
    questionImageFilename: undefined,
    optionAImageFilename: undefined,
    optionBImageFilename: undefined,
    optionCImageFilename: undefined,
    optionDImageFilename: undefined,
    status: "DRAFT",
  };
  if (mode !== "RICH") return row;

  const review = q.review;
  let reviewFlag: string | undefined;
  let reviewReason: string | undefined;
  if (review !== undefined) {
    if (!isObj(review) || (review.required !== undefined && typeof review.required !== "boolean")) fail(c, "review", 'must be {"required": true|false, "reason": "…"}.');
    else {
      reviewFlag = review.required === true ? "TRUE" : review.required === false ? "FALSE" : undefined;
      reviewReason = text(c, "review.reason", review.reason) || undefined;
    }
  }
  let listI: string | undefined;
  let listII: string | undefined;
  if (q.matchLists !== undefined) {
    if (!isObj(q.matchLists)) fail(c, "matchLists", 'must be {"listI": […], "listII": […]}.');
    else {
      for (const k of Object.keys(q.matchLists)) if (k !== "listI" && k !== "listII") fail(c, `matchLists.${k}`, "unknown field.");
      listI = matchList(c, "matchLists.listI", q.matchLists.listI) || undefined;
      listII = matchList(c, "matchLists.listII", q.matchLists.listII) || undefined;
    }
  }
  const opt = (s: string) => s || undefined;
  return {
    ...row,
    questionImageFilename: opt(question.images),
    optionAImageFilename: opt(byLabel.A?.images ?? ""),
    optionBImageFilename: opt(byLabel.B?.images ?? ""),
    optionCImageFilename: opt(byLabel.C?.images ?? ""),
    optionDImageFilename: opt(byLabel.D?.images ?? ""),
    contentFormat: opt(scalar(c, "contentFormat", pick("contentFormat"))),
    questionType: opt(scalar(c, "type", pick("type"))),
    paperCode: opt(scalar(c, "paperCode", pick("paperCode"))),
    explanationImages: opt(explanation.images),
    reviewFlag,
    reviewReason,
    listI,
    listII,
  };
}

/**
 * Parses a JSON question document into BulkImportRow[] (rowNumber = position
 * in `questions`, 1-based). Throws JsonImportError listing every structural
 * problem; never returns a partial file.
 */
export function parseJsonQuestions(source: string, mode: ImportParseMode = "LEGACY"): BulkImportRow[] {
  if (Buffer.byteLength(source, "utf8") > JSON_IMPORT_LIMITS.maxBytes) throw new JsonImportError([`The JSON file is larger than ${JSON_IMPORT_LIMITS.maxBytes / 1024 / 1024} MB.`]);
  let doc: Json;
  try {
    doc = JSON.parse(source.replace(/^﻿/, "")) as Json;
  } catch (e) {
    throw new JsonImportError([`The file is not valid JSON (${e instanceof Error ? e.message : "parse error"}).`]);
  }
  if (depthOf(doc) > JSON_IMPORT_LIMITS.maxDepth) throw new JsonImportError(["The JSON file is nested too deeply."]);

  let defaults: Obj = {};
  let questions: Json[];
  if (Array.isArray(doc)) questions = doc;
  else if (isObj(doc)) {
    for (const k of Object.keys(doc)) if (!["schema", "defaults", "questions"].includes(k)) throw new JsonImportError([`Unknown top-level field "${k}" (expected schema, defaults, questions).`]);
    if (doc.schema !== undefined && doc.schema !== JSON_IMPORT_SCHEMA) throw new JsonImportError([`Unsupported schema "${String(doc.schema)}" — this importer reads "${JSON_IMPORT_SCHEMA}".`]);
    if (doc.defaults !== undefined) {
      if (!isObj(doc.defaults)) throw new JsonImportError(['"defaults" must be an object.']);
      const bad = Object.keys(doc.defaults).filter((k) => !DEFAULT_KEYS.has(k));
      if (bad.length) throw new JsonImportError([`"defaults" cannot set ${bad.map((k) => `"${k}"`).join(", ")} (allowed: ${[...DEFAULT_KEYS].join(", ")}).`]);
      defaults = doc.defaults;
    }
    if (!Array.isArray(doc.questions)) throw new JsonImportError(['"questions" must be an array.']);
    questions = doc.questions;
  } else throw new JsonImportError(['The JSON file must be an object with "questions" (or an array of questions).']);

  if (questions.length === 0) throw new JsonImportError(["The JSON file has no questions."]);
  if (questions.length > JSON_IMPORT_LIMITS.maxQuestions) throw new JsonImportError([`The JSON file has ${questions.length} questions (max ${JSON_IMPORT_LIMITS.maxQuestions}). Split it.`]);

  const problems: string[] = [];
  const rows = questions.map((q, i) => toRow(q, i, defaults, mode, problems));
  // Rich validation already reports a code repeated in one file per row; Standard mode
  // has no such check (only codes already in the bank), so a JSON file refuses it here.
  if (mode === "LEGACY") {
    const seen = new Map<string, number>();
    rows.forEach((r, i) => {
      if (!r?.questionCode) return;
      const key = r.questionCode.toLowerCase();
      const first = seen.get(key);
      if (first !== undefined) problems.push(`Question ${i + 1} › code: "${r.questionCode}" is already used by question ${first}. Every question needs a unique code.`);
      else seen.set(key, i + 1);
    });
  }
  if (problems.length) throw new JsonImportError(problems);
  return rows.filter((r): r is BulkImportRow => r !== null);
}

/** Picks the one `questions.json` of a ZIP package (any folder; OS junk is not listed by the caller). */
export function findPackageManifest<T extends { name: string; basename: string }>(entries: T[]): T {
  const hits = entries.filter((e) => e.basename.toLowerCase() === JSON_PACKAGE_MANIFEST);
  if (hits.length === 0) throw new JsonImportError([`The ZIP package has no ${JSON_PACKAGE_MANIFEST}.`]);
  if (hits.length > 1) throw new JsonImportError([`The ZIP package has ${hits.length} files named ${JSON_PACKAGE_MANIFEST} — keep exactly one.`]);
  return hits[0];
}
