import { Sparkles } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { prisma } from "@/lib/prisma";
import { getAiSettings } from "@/lib/ai-settings";
import type { ExplanationContent } from "@/lib/ai-explanation";

const SECTION_WRAP = "mx-auto w-full max-w-6xl px-4 py-14 sm:px-6 sm:py-20";

/**
 * Public homepage preview of Ask AI. Anonymous visitors never trigger live
 * generation here — this only ever renders explanations that already exist
 * (status COMPLETED), that an admin has explicitly marked reviewed
 * (adminReviewedAt set, via the "Mark Reviewed" control on AI Solutions),
 * and that haven't gone stale since (isStale false — see
 * lib/ai-explanation.ts#flagExplanationStaleIfExists).
 * Count is admin-configurable (ai.settings.homepageDemoMaxQuestions) but
 * capped at 12 server-side regardless of what's stored.
 */
export async function AskAiDemoSection() {
  const settings = await getAiSettings();
  if (!settings.homepageDemoEnabled) return null;

  const take = Math.min(12, Math.max(0, settings.homepageDemoMaxQuestions));
  if (take === 0) return null;

  const rows = await prisma.aIExplanation.findMany({
    where: { status: "COMPLETED", adminReviewedAt: { not: null }, isStale: false },
    orderBy: { adminReviewedAt: "desc" },
    take,
    select: {
      content: true,
      question: { select: { code: true, text: true } },
    },
  });

  if (rows.length === 0) return null;

  return (
    <section className="border-t border-[var(--color-border)] bg-[var(--color-surface)]">
      <div className={SECTION_WRAP}>
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-[var(--color-primary)]" aria-hidden />
          <h2 className="text-2xl text-[var(--color-foreground)] sm:text-3xl">Ask AI in Action</h2>
        </div>
        <p className="mt-2 max-w-2xl text-[var(--color-muted-foreground)]">
          Real, admin-reviewed explanations generated by Ask AI — sign up to ask on any question.
        </p>

        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {rows.map((row, i) => {
            const content = row.content as unknown as ExplanationContent;
            return (
              <Card key={i}>
                <CardContent className="flex flex-col gap-2 p-4">
                  <Badge variant="neutral" className="w-fit">
                    {row.question.code}
                  </Badge>
                  <p className="line-clamp-2 text-sm font-medium text-[var(--color-foreground)]">{row.question.text}</p>
                  {content?.concept ? (
                    <p className="line-clamp-4 text-sm text-[var(--color-muted-foreground)]">{content.concept}</p>
                  ) : null}
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </section>
  );
}
